; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
monitor_filters = esp32_exception_decoder
build_type = debug
lib_deps = 
	knolleary/PubSubClient@^2.8
	adafruit/Adafruit MLX90640@^1.1.2
	bblanchon/ArduinoJson@^7.2.2
	nkawu/TFT 22 ILI9225@^1.4.5
	adafruit/DHT sensor library@^1.4.7
	https://github.com/DFRobot/DFRobot_GestureFaceDetection.git
	https://github.com/DFRobot/DFRobot_HumanDetection.git
	https://github.com/Fiooodooor/HLK-LD245X.git
	denyssene/SimpleKalmanFilter@^0.1.0
